// Generated by CoffeeScript 1.8.0
var normalizePathSeparator, path;

path = require('path');

normalizePathSeparator = function(filePath) {

  /*
  применяется для преобразования пути в юникс стайл для Windows
   */
  if (path.sep !== '/') {
    return filePath.split(path.sep).join('/');
  } else {
    return filePath;
  }
};

module.exports = normalizePathSeparator;
